# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 00:16
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='label')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('RUR', 'Russian Rouble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='RUR', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tr_type', models.SmallIntegerField(choices=[(1, 'add'), (2, 'withdraw'), (3, 'move')])),
                ('tr_tag', models.SmallIntegerField(choices=[(1, 'Equity'), (2, 'Asset'), (3, 'Liability'), (4, 'Income'), (5, 'Expense')])),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('RUR', 'Russian Rouble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='RUR', max_length=3)),
                ('tr_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BankAccount')),
                ('tr_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_to', to='accounts.BankAccount')),
            ],
        ),
    ]
