# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tr_tag',
            new_name='tr_tags',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tr_type',
            field=models.SmallIntegerField(choices=[(1, 'Add'), (2, 'Withdraw'), (3, 'Move'), (4, 'Exchange')]),
        ),
    ]
