# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:50
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171204_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tr_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
