# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171205_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('other_currency', models.CharField(max_length=3)),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
