# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
