# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('RUR', 'Russian Rouble'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='RUR', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
