# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
