# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tr_tag',
            field=models.SmallIntegerField(choices=[(0, ''), (1, 'Equity'), (2, 'Asset'), (3, 'Liability'), (4, 'Income'), (5, 'Expense')]),
        ),
    ]
